# Generated by Django 4.1 on 2025-11-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitlog',
            name='excluded',
            field=models.BooleanField(default=False),
        ),
    ]
