# Generated by Django 4.1 on 2025-11-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habitlog_excluded'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='accumulated_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='habit',
            name='last_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='timer_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='timer_state',
            field=models.CharField(default='stopped', max_length=20),
        ),
    ]
